### ISSUE TITLE
Account connection issue

### ISSUE THREAD

**Issue by Faeziix** [sidorares/node-pidgin#3]
I am trying to connect to an account and I am following libpurple tutorial but I am constantly getting this message in debug page.

> account: Account <account> not enabled, not connecting

Here is the code

```javascript 
  p.PurpleAccountNew(
    "<email>",
    "prpl-eionrobb-discord",
    (err, acc) => {
      p.PurpleAccountSetPassword(acc, "<password>");
      p.PurpleAccountsAdd(acc);
      p.PurpleAccountSetEnabled(acc, "user", true);
      p.PurpleAccountConnect(acc);
    }
  );
```

**Comment by sidorares** [comment]
Can you try to wait for `PurpleAccountSetEnabled` success before `PurpleAccountConnect` call? ( e.i move `p.PurpleAccountConnect(acc);` into PurpleAccountSetEnabled callback:

something along the lines (not tested, just an illustration)
```js
p.PurpleAccountNew(
    "<email>",
    "prpl-eionrobb-discord",
    (err, acc) => {
      p.PurpleAccountSetPassword(acc, "<password>");
      p.PurpleAccountsAdd(acc);
      p.PurpleAccountSetEnabled(acc, "user", true, (err) => {
        p.PurpleAccountConnect(acc);
      });
    }
  );
```

**Comment by Faeziix** [comment]
I tried it but still giving me the same error.

**Comment by Faeziix** [comment]
I found the solution. The problem was with value of PurpleAccountSetEnabled. It should've been equal to 1 not true. and also added ui-code as well. 
```javascript
p.PurpleAccountNew(
    "<email>",
    "prpl-eionrobb-discord",
    (err, acc) => {
      p.PurpleAccountSetPassword(acc, "<password>");
      p.PurpleAccountsAdd(acc);
      p.PurpleCoreGetUi((err, ui) => {
        p.PurpleAccountSetEnabled(acc, ui, 1);
      });
    }
  );

```

**Comment by sidorares** [comment]
thanks for sharing that @Faeziix . I wonder is it something that incorrectly handled by dbus client or on a Pibgin side

at a marshalling level, per [spec](https://dbus.freedesktop.org/doc/dbus-specification.html#basic-types):

`
BOOLEAN | b (98) | Boolean value: 0 is false, 1 is true, any other value allowed by the marshalling format is invalid
`

if the type returned by introspection is BOOLEAN the driver should probably assist in converting to 0/1 ( or at least show meaningful error instead )

I'll try to investigate that but if you have time to dig this @Faeziix that would be great

**Comment by Faeziix** [comment]
In libpurple tutorial they were setting the value to true that's why I set it as well. I am not really good at technicality behind the dbus and introspection but I try to investigate it.
